### ISSUE TITLE
Autofocus TOPT field

### ISSUE THREAD

**Issue by iandunn** [ivankruchkoff/google-authenticator#11]
When the TOPT field is on the second screen, and the user is redirected to it after entering their username/password, they have to tab to the field before they can start typing.

Since it's the first input on the field, [it makes sense to `autofocus` it](https://ux.stackexchange.com/a/60027/13828). I always assume it's autofocused and start typing while looking at the code on my phone, then discover that nothing was entered because I'm not focused on it.

**Comment by joldnl** [comment]
All big things have small beginnings :D. Its a small update but makes a big impact. I always just type in the code, to discover that the field wasn't focussed, and enter the code twice.

**Comment by ivankruchkoff** [comment]
Merged and resolved
