### ISSUE TITLE
Assign users the Subscriber role until they enable 2FA (if it's required)

### ISSUE THREAD

**Issue by jordif** [ivankruchkoff/google-authenticator#12]
Hi,

first, thanks for maintaining this plugin!

So far, I have used this plugin together with @iandunn's plugin ( Google Authenticator – Encourage User Activation ).

With version 0.50, some of the features provided by Ian's plugin are now built-in (requiring user activation and redirecting users to the setup page).

The only thing that seems to be missing is completely preventing users from doing anything (through XML-RPC, AJAX, JSON API) by assignin them the Subscriber role.

Would it be possible/useful to add this feature?

Thanks!

**Comment by ivankruchkoff** [comment]
@jordif I think that may break functionality, especially since json api can be accessed without auth. Not sure how to build an auth interface for endpoints like the one you mentioned without making functionality painful for users, e.g. requiring a totp everytime they want to make an api request.
