### ISSUE TITLE
assigned role, user could not upload photo

### ISSUE THREAD

**Issue by touy** [ivankruchkoff/google-authenticator#14]
Hi 
I got a problem with my woocomerce, which when I use google authentication, it's very useful. But I have found some bugs 
1. when I assigned to some roles , if users that i didn't turn on google authentication , user could not upload photo , it seems it didn't passed the google authentication , 
- but a user with google authentication  , it could work nicely , so I think your code should by pass this when that user didn't use google authentication
- when I unchecked (default) hide this setting to user, from user view I could not see this setting , which there is no option for user for this google authentication 
I hope to fix that bug and make it complete

**Comment by ivankruchkoff** [comment]
Hi @touy not sure I understand the issue, if the user is able to login, they are able to upload photo.
