### ISSUE TITLE
Fatal error on login with admin account - customer login form

### ISSUE THREAD

**Issue by ReadySetOdds** [ivankruchkoff/google-authenticator#19]
Hey there! I'm getting a fatal error message whenever I login from the regular login form, the one where customers login from, with my admin credentials. 

> Fatal error: Uncaught Error: Call to undefined function login_header() in /home/ikternet/public_html/readysetodds.com/wp-content/plugins/google-authenticator/google-authenticator.php:634 Stack trace: #0 /home/ikternet/public_html/readysetodds.com/wp-content/plugins/google-authenticator/google-authenticator.php(621): GoogleAuthenticator->secondary_login_screen() #1 /home/ikternet/public_html/readysetodds.com/wp-includes/class-wp-hook.php(288): GoogleAuthenticator->check_otp(Object(WP_User), '_USERNAME_HERE_', '_PASSWORD_HERE_') #2 /home/ikternet/public_html/readysetodds.com/wp-includes/plugin.php(206): WP_Hook->apply_filters(Object(WP_User), Array) #3 /home/ikternet/public_html/readysetodds.com/wp-includes/pluggable.php(539): apply_filters('authenticate', NULL, '_USERNAME_HERE_', '_PASSWORD_HERE_') #4 /home/ikternet/public_html/readysetodds.com/wp-includes/user.php(95): wp_authenticate('_USERNAME_HERE_', '_PASSWORD_HERE_') #5 /home/ikternet/public_html/readysetodds.com/wp-content/plugins/woocommerce/includes/class-wc-form- in /home/ikternet/public_html/readysetodds.com/wp-content/plugins/google-authenticator/google-authenticator.php on line 634

Whenever I login from the actual login page there's no errors.

**Comment by ivankruchkoff** [comment]
Hi @ReadySetOdds I think that's an issue with your theme, have a look at https://developer.wordpress.org/reference/functions/login_header/
