### ISSUE TITLE
php 8.1 and 8.2 deprecation notice

### ISSUE THREAD

**Issue by chrillep** [ivankruchkoff/google-authenticator#32]
LevelAllWarningNoticeStrictDeprecated | Message | Location | Count | ComponentAllMU Plugin: kinsta-mu-pluginsPlugin: google-authenticator
-- | -- | -- | -- | --
Deprecated | strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated | +wp-includes/functions.php:7053 | 1 | Plugin: google-authenticator
Deprecated | str_replace(): Passing null to parameter #3 ($subject) of type array\|string is deprecated | +wp-includes/functions.php:2165 | 1 | Plugin: google-authenticator

refs
* https://wordpress.org/support/topic/php-8-2-depreacation-notice/

**Comment by ivankruchkoff** [comment]
Thanks for raising, thanks for the PR to resolve this.
