### ISSUE TITLE
Inconsistent writting

### ISSUE THREAD

**Issue by glkx** [ivankruchkoff/google-authenticator#4]
While translating the plugin to Dutch I came across a lot of inconsistent writing. Examples are:
- Google Authenticator or Authenticator
- Phone or device

Don't know if it's feasible with all different translations already created. For UX purposes it would definitely be great though.

**Comment by ivankruchkoff** [comment]
@glkx I agree with you that consistency is preferred, however, as you've pointed out, translations already exist for the current copy, and I think preserving those strings, rather than leaving a fallback to English would be better.
