### ISSUE TITLE
App password does not work anymore

### ISSUE THREAD

**Issue by aryasenna** [ivankruchkoff/google-authenticator#5]
Can anyone confirm if the generated app password no longer work with latest version of WP and this plugin?

Would be happy to provide more info and logs.

**Comment by ivankruchkoff** [comment]
@aryasenna yes, that was a regression in 0.50, can you try 0.51 and let me know if you're still facing the issue?

**Comment by aryasenna** [comment]
Hi there 0.51 fixed the issue. Thanks for quick response. I'll just close the issue.
